version: '3.8'

x-common-deploy: &common-deploy
  mode: global
  update_config:
    delay: 0s
    order: stop-first
    failure_action: continue
  restart_policy:
    condition: on-failure
    delay: 5s
    max_attempts: 5
    window: 120s

x-deploy: &deploy
  deploy:
    <<: *common-deploy
    placement:
      constraints:
        - node.labels.${APP_NAME}==1

services:
  proxy:
    <<: [*deploy]
    image: ${DOCKER_REGISTRY}/${DOCKER_REPOSITORY}/${APP_NAME}-proxy:latest
    hostname: "proxy"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
    networks:
      - dmz
      - registryipv4
    # not used, while "dmz" is an external bridge network scope=swarm, these
    # ports are made on the swarm's ingress network, which is currently ipv4
    # only, hence the DOCKER-INGRESS in iptables ipv4 is the only change, not
    # ipv6
    ports:
      - "[::]:1443:443"
    configs:
      - source: registry-proxy-config
        target: /etc/nginx/nginx.conf
    secrets:
      - source: registry-https-crt
        target: /etc/nginx/certs/crt_.pem
      - source: registry-https-key
        target: /etc/nginx/certs/key_.pem
      - source: registry-auth-htpasswd
        target: /auth/htpasswd

  registry:
    <<: [*deploy]
    image: registry:2
    init: true
    hostname: "registry"
    secrets:
      - source: registry-https-crt
        target: /certs/registry.crt
      - source: registry-https-key
        target: /certs/registry.key
      - source: registry-auth-htpasswd
        target: /auth/htpasswd
    volumes:
      - registry-data:/var/lib/registry
    networks:
      - registryipv4
    environment:
      REGISTRY_LOG_LEVEL: "debug"
      REGISTRY_HTTP_ADDR: "\"0.0.0.0:5000\""
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/registry.crt
      REGISTRY_HTTP_TLS_KEY: /certs/registry.key
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_HTTP_SECRET: ${REGISTRY_HTTP_SECRET}

volumes:
  registry-data:
    name: registry-data-${APP_NAME}
    driver: local
    driver_opts:
      type: none
      device: /mnt/ssd/docker-registry
      o: bind

# see https://github.com/moby/moby/issues/24379
# see https://serverfault.com/questions/933211/how-to-create-docker-ingress-network-with-ipv6-support
# see https://labs.ripe.net/author/tugzrida/docker-ipv6-networking-routing-and-ndp-proxying/
networks:
  dmz:
    name: dmz-${APP_NAME}
    external: true
  registryipv4:
    driver: overlay
    attachable: true
    driver_opts:
      encrypted: "1"
      gateway: 10.10.2.1
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 10.10.2.0/24

secrets:
  registry-https-crt:
    name: registry-https-crt-${CFG_PREFIX}
    external: true
  registry-https-key:
    name: registry-https-key-${CFG_PREFIX}
    external: true
  registry-auth-htpasswd:
    name: registry-auth-htpasswd-${CFG_PREFIX}
    external: true

configs:
  registry-proxy-config:
    name: registry-proxy-config-${CFG_PREFIX}
    external: true
